const whitelist = {
    'array': 1,
    'collaboration': 1,
    'meetup': 1,
    'documentation': 1,
    'object': 1,
    'function':1,
    'testem':1,
    'terminal':1,
    'test spec':1,
    'grades':1,
    'checkpoint':1,
    'git':1,
    'vs code':1,
    'hoisting':1,
    'error':25,
    'npm':28,
    'eslint':31,
    'logistics':32,
    'recursion':39,
    'type':41,
    'ropedude':46,
}

module.exports = whitelist;