const whitelist = {
    'array': 1,
    'reduce': 2,
    'collaboration': 3,
    'group': 4,
    'meetup': 5,
    'documentation': 7,
    'loop': 8,
    'object': 9,
    'map':10,
    'time':11,
    'function':12,
    'testem':29,
    'console':14,
    'call stack':15,
    'foreach':16,
    'test spec':17,
    'grades':18,
    'checkpoint':19,
    'github':20,
    'kb':21,
    'vs code':22,
    'slack':23,
    'permission':24,
    'error':25,
    'idea':26,
    'workshop':27,
    'npm':28,
    'suggestion':30,
    'eslint':31,
    'curl':32,
    'path':33,
    'node':34,
    'laptop':35,
    'sudo':36,
    'warning':37,
    'string':38,
    'recursion':39,
    'stringify':40,
    'type':41,
    'concat':42,
    'arguments':43,
    'parameter':44,
    'callbacks':45,
    'ropedude':46,
    'bash':47,
    'python':48,
}

module.exports = whitelist;