const whitelist = {
    'array': 1,
    'reduce': 1,
    'collaboration': 1,
    'group': 1,
    'meetup': 1,
    'documentation': 1,
    'loop': 1,
    'object': 1,
    'map':1,
    'time':1,
    'function':1,
    'testem':1,
    'console':1,
    'call stack':1,
    'foreach':1,
    'test spec':1,
    'grades':1,
    'checkpoint':1,
    'study':1,
    'github':1,
    'kb':1,
    'vs code':1,
    'hoisting':1,
    'slack':1,
    'permission':24,
    'error':25,
    'idea':26,
    'workshop':27,
    'npm':28,
    'suggestion':30,
    'eslint':31,
    'curl':32,
    'path':33,
    'node':34,
    'laptop':35,
    'sudo':36,
    'warning':37,
    'string':38,
    'recursion':39,
    'stringify':40,
    'type':41,
    'concat':42,
    'arguments':43,
    'parameter':44,
    'callbacks':45,
    'ropedude':46,
    'bash':47,
    'python':48,
}

module.exports = whitelist;