export const EDIT_CONVERSATION = Symbol('EDIT_CONVERSATION');

export const GET_CONVERSATION = Symbol('GET_CONVERSATION');

export const GET_ALL_CONVERSATIONS = Symbol('GET_ALL_CONVERSATIONS');

export const REMOVE_CONVERSATION = Symbol('REMOVE_CONVERSATION');